version: "3.3"

services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.12.1
        environment:
            - discovery.type=single-node
        ports:
            - 9200:9200
            - 9300:9300

    personal_blog:
        image: personal_blog
        volumes:
            - ~/Projects/personal_blog/personal_blog/static:/home/personal_blog/personal_blog/static:rw
        environment:
            - SECRET_KEY=$SECRET_KEY 
            - DATABASE_URI=$DATABASE_URI 
            - MAIL_USERNAME=$MAIL_USERNAME
            - MAIL_PASSWORD=$MAIL_PASSWORD
            - ELASTICSEARCH_URL=$ELASTICSEARCH_URL
        ports:
            - 8000:5000
        depends_on:
            - elasticsearch
