"""empty message

Revision ID: 862fffc39a5f
Revises: 
Create Date: 2021-03-05 12:50:10.656909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '862fffc39a5f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_book_title'), 'book', ['title'], unique=False)
    op.create_index(op.f('ix_comment_date_posted'), 'comment', ['date_posted'], unique=False)
    op.create_index(op.f('ix_post_date_posted'), 'post', ['date_posted'], unique=False)
    op.create_index(op.f('ix_post_title'), 'post', ['title'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_post_title'), table_name='post')
    op.drop_index(op.f('ix_post_date_posted'), table_name='post')
    op.drop_index(op.f('ix_comment_date_posted'), table_name='comment')
    op.drop_index(op.f('ix_book_title'), table_name='book')
    # ### end Alembic commands ###
